### PR TITLE
naming change to existing functionality

### PR DESCRIPTION
**Pull request by NSmeef**

### CODE REVIEW

**Comment by dcmwong** [comment]
Is this the last modified date as in the date it was last saved or the date is was last published?

**Comment by NSmeef** [comment]
Last saved.

**Comment by dcmwong** [comment]
Had thoughts of making this more apparent rather than on the info button.  Maybe something like a toastr?

http://codeseven.github.io/toastr/demo.html

**Comment by NSmeef** [comment]
Yeh, you can build upon this later on. Do we need that yet?

**Comment by dcmwong** [comment]
ok

**Pull request merged**
